{: \GPL-3.0-only : b<https://www.gnu.org/licenses/> :}
{: \Apache-2.0 : b<https://www.apache.org/licenses/LICENSE-2.0.html> :}
{: \CC-BY-4.0 : b<https://creativecommons.org/licenses/by/4.0/> :}
{: \CC0 : b<https://creativecommons.org/publicdomain/zero/1.0/> :}

{: \stroke-input-version: v0.9.10 :}
{: \stroke-input-year: 2021--2022 :}
{: \stroke-input-url :
  https://github.com/stroke-input/stroke-input-android
:}
@@[Stroke Input Method] \stroke-input-url @@
@@[筆畫輸入法] \stroke-input-url @@
@@[笔画输入法] \stroke-input-url @@

@@[`Keyboard.java`]
  https://android.googlesource.com/platform/frameworks/base/+/\
    33f921769531968a3ba9bc73fb2410f95868cb8d/\
    core/java/android/inputmethodservice/Keyboard.java
@@
@@[`KeyboardView.java`]
  https://android.googlesource.com/platform/frameworks/base/+/\
    33f921769531968a3ba9bc73fb2410f95868cb8d/\
    core/java/android/inputmethodservice/KeyboardView.java
@@

{: \material-version : v1.5.0 :}
{: \material-year : 2021 :}
@@[Material Components For Android]
  https://mvnrepository.com/artifact/com.google.android.material/material
@@

{: \stroke-data-version : v1.7.0 :}
{: \sequence-characters-year : 2021--2022 :}
@@[Conway Stroke Data]
  https://github.com/stroke-input/stroke-input-data
@@

{: \stroke-font-version : v2.0.1 :}
{: \stroke-font-year : 2021--2022 :}
@@[Stroke Input Font]
  https://github.com/stroke-input/stroke-input-font
@@

{: \noto-cjk-url :
  https://github.com/googlefonts/noto-cjk/\
    tree/2663656870e92c0dcbe891590681815ebb509c05
:}
@@[2015 version of Noto Sans CJK TC] \noto-cjk-url @@
@@[2015 版 <span class="en">Noto Sans CJK TC</span>] \noto-cjk-url @@

@@[CMD]
  https://github.com/conway-markdown/conway-markdown
@@

{: \cmd-source :
  [<code>%cmd-name-file.cmd</code>](
    https://github.com/stroke-input/stroke-input-android/blob/master/\
      %cmd-name.cmd
  )
:}
