name: Build app-debug.apk

on:
  push:
    branches: [master]
    paths-ignore:
      - "LICENSE"
      - "*.md"
      - "fastlane/**"
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - run: ./gradlew clean && ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
